# ArgoCD - GitOps continuous delivery
#
# config.nix:
#   services.argocd = true;
#
# URL: https://argocd.<subdomain>.<domain>
# Login: admin / <auto-generated password stored in K8s secret>
#   To retrieve it: kubectl -n argo-cd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
{ config, lib, pkgs, serverConfig, ... }:

let
  k8s = import ../lib.nix { inherit pkgs serverConfig; };
in
k8s.createHelmRelease {
  name = "argocd";
  namespace = "argo-cd";
  repo = {
    name = "argo-cd";
    url = "https://argoproj.github.io/argo-helm";
  };
  chart = "argo-cd/argo-cd";
  version = "7.7.10";
  tier = "core";
  values = {
    server = {
      service.type = "ClusterIP";
    };
    configs.params = {
      "server.insecure" = true; # TLS terminated at Traefik
    };
  };
  ingress = {
    host = "argocd";
    service = "argocd-server";
    port = 80;
  };
  waitFor = "argocd-server";
}
