apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-manager
  namespace: __NAMESPACE__
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale", "statefulsets/scale"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["traefik.io", "traefik.containo.us"]
    resources: ["ingressroutes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-manager
subjects:
  - kind: ServiceAccount
    name: service-manager
    namespace: __NAMESPACE__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-manager
  namespace: __NAMESPACE__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-manager
  template:
    metadata:
      labels:
        app: service-manager
    spec:
      serviceAccountName: service-manager
      containers:
      - name: service-manager
        image: docker.io/library/service-manager:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            memory: 64Mi
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: service-manager-config
---
apiVersion: v1
kind: Service
metadata:
  name: service-manager
  namespace: __NAMESPACE__
spec:
  selector:
    app: service-manager
  ports:
  - port: 8080
    targetPort: 8080
