apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
    - cidr: __POD_CIDR__
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
